# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "<NAME>"
    config.vm.box = "davbfr/<NAME>"
    config.ssh.username = "root"
end
